### ISSUE TITLE
SCPI Command Handler

### ISSUE THREAD

**Issue by ztnel** [dronectl/raptor#11]
# Description
SCPI (Standardized Command for Programmable Instruments) appears to be the primary choice for implementing a command wrapper for an embedded system integration test platform. The goal is to develop a scpi command handler which is capable of being memory configurable to support a variety of programmable and measurement endpoints. TCP/IP will be the interface medium for SCPI commands. 

Input Stream -> String Parser -> Command Filtration -> Function Selection -> Parameter -> Function Execution -> Result / Return Code -> Output Stream

## Verification
Ensure the system can respond to scpi commands sent out by general purpose open source libraries such as [`lxi-tools`](https://github.com/lxi-tools/lxi-tools) and [`PyVISA`](https://github.com/pyvisa/pyvisa)

## Tasks
 - [ ] SCPI string parser (support common SCPI syntax)
 - [ ] Create memory map for command hierarchy
 - [ ] Create function execution handlers with standardized error codes
