### ISSUE TITLE
Port Firmware to STM32F411 ARM

### ISSUE THREAD

**Issue by ztnel** [dronectl/raptor#19]
# Description
This is a relatively large task which involves rewriting the firmware to support an `arm` processor over an `avr` processor. This shift is critical for unlocking RTOS and more advanced OCD capabilities. The original ATMEGA328p was a simple MCU which was chosen due to its simplicity in getting up and running but the functional requirements suggest we will need a much bigger MCU and potentially powered by an RTOS.

## Tasks
 - [ ] Rewrite toolchain to work with  `arm-none-eabi-gcc`
 - [ ] Integrate debugging tools using`cortex-debug` vscode extension
 - [ ] Rewrite the SPI driver for STM32F411
 - [ ] Rewrite USART driver for STM32F411
